<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio Filtrado de Datos

En este laboratorio usaremos el DataFrame creado en la lección anterior resultado de la unión de los conjuntos de datos compartidos contigo. 

**Instrucciones:**

1. Lee cuidadosamente el enunciado de cada ejercicio.

2. Implementa la solución en la celda de código proporcionada.

In [197]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

df_union_final = pd.read_csv("datos/df_union_final.csv", index_col = 0)

In [198]:
df_union_final

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
0,s2037,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,NaN,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ...",NaN,NaN,NaN,NaN,NaN
1,s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,NaN,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol...",NaN,NaN,NaN,NaN,NaN
2,s2482,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,NaN,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ...",NaN,NaN,NaN,NaN,NaN
3,s2325,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...,NaN,NaN,NaN,NaN,NaN
4,s5974,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,NaN,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s6178,TV Show,忍者ハットリくん,NaN,NaN,Japan,"December 23, 2018",2012,TV-Y7,2 Seasons,"Anime Series, Kids' TV","Hailing from the mountains of Iga, Kanzo Hatto...",NaN,NaN,NaN,NaN,NaN
8803,s4915,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-14,NaN,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh...",NaN,NaN,NaN,NaN,NaN
8804,s7102,TV Show,마녀사냥,NaN,"Si-kyung Sung, Se-yoon Yoo, Dong-yup Shin, Ji-...",South Korea,"February 19, 2018",2015,TV-MA,NaN,"International TV Shows, Korean TV Shows, Stand...",Four Korean celebrity men and guest stars of b...,NaN,NaN,NaN,NaN,NaN
8805,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...,NaN,NaN,NaN,NaN,NaN
8806,s7109,Movie,최강전사 미니특공대 : 영웅의 탄생,Young Jun Lee,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,"September 1, 2018",2018,TV-Y7,68 min,Children & Family Movies,"Miniforce, a special task force of elite range...",NaN,NaN,NaN,NaN,NaN

#### Ejercicio 1: ¿Cuáles son todos los títulos lanzados en 2021 que son del tipo 'Movie'?

In [199]:
df_Movie = df_union_final.loc[df_union_final.type == "Movie"]
df_2021 = df_Movie[df_Movie.release_year == 2021] 
df_2021

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
128,s1151,Movie,7 Yards: The Chris Norton Story,Jonathon Link,Chris Norton,United States,"March 30, 2021",2021,TV-PG,NaN,Documentaries,The true story of former college football play...,NaN,NaN,NaN,NaN,NaN
141,s851,Movie,99 Songs,Vishwesh Krishnamoorthy,"Ehan Bhat, Edilsy Vargas, Manisha Koirala, Lis...",India,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...,NaN,NaN,NaN,NaN,NaN
142,s852,Movie,99 Songs (Tamil),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...,NaN,NaN,NaN,NaN,NaN
143,s853,Movie,99 Songs (Telugu),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...,NaN,NaN,NaN,NaN,NaN
144,s405,Movie,9to5: The Story of a Movement,NaN,NaN,NaN,"July 22, 2021",2021,TV-MA,85 min,Documentaries,"In this documentary, female office workers in ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8662,s113,Movie,Worth,Sara Colangelo,"Michael Keaton, Stanley Tucci, Amy Ryan, Shuno...",NaN,"September 3, 2021",2021,PG-13,119 min,Dramas,"In the wake of the Sept. 11 attacks, a lawyer ...",NaN,NaN,NaN,NaN,NaN
8678,s1320,Movie,Xico's Journey,Eric D. Cabello Díaz,"Verónica Alva, Pablo Gama Iturrarán “Mago Gami...",Mexico,"February 12, 2021",2021,TV-Y7,NaN,Children & Family Movies,"A girl, a dog and her best pal set out to save...",NaN,NaN,NaN,NaN,NaN
8679,s766,Movie,Xtreme,Daniel Benmayor,"Teo García, Óscar Jaenada, Óscar Casas, Andrea...",Spain,"June 4, 2021",2021,TV-MA,112 min,"Action & Adventure, International Movies","In this fast-paced and action-packed thriller,...",NaN,NaN,NaN,NaN,NaN
8682,s1219,Movie,YES DAY,Miguel Arteta,"Jennifer Garner, Edgar Ramírez, Jenna Ortega, ...",United States,"March 12, 2021",2021,PG,90 min,"Children & Family Movies, Comedies",A mom and dad who usually say no decide to say...,NaN,NaN,NaN,NaN,NaN
8723,s76,Movie,You vs. Wild: Out Cold,Ben Simms,"Bear Grylls, Jason Derek Prempeh",NaN,"September 14, 2021",2021,TV-G,NaN,Children & Family Movies,"After a plane crash leaves Bear with amnesia, ...",NaN,NaN,NaN,NaN,NaN

#### Ejercicio 2: ¿Qué títulos tienen una duración de 90 minutos? Muestra solo las columnas de título y de duración.

In [200]:
df_90 = df_union_final.loc[df_union_final.duration == "90 min"]
df_90[["title", "duration"]]

                                        title duration
9                            #cats_the_mewvie   90 min
29                               12 ROUND GUN   90 min
32                                 13 Cameras   90 min
52                                        1BR   90 min
155                          A Champion Heart   90 min
...                                       ...      ...
8572                               White Girl   90 min
8586          Who's That Knocking at My Door?   90 min
8682                                  YES DAY   90 min
8697                               Yellowbird   90 min
8749  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   90 min

[152 rows x 2 columns]

#### Ejercicio 3: ¿Cuáles son todos los títulos del país 'India' lanzados después de 2018?

In [201]:
df_india = df_union_final.loc[df_union_final.country == "India"]
df_india_2018 = df_india.loc[df_india.release_year >= 2018]
df_india_2018

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
41,s3963,Movie,15 August,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ...",Comedy-drama,"March 29, 2019",124.0,5.8,Marathi
42,s5967,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ...",NaN,NaN,NaN,NaN,NaN
68,s6002,TV Show,21 Sarfarosh: Saragarhi 1897,NaN,"Luke Kenny, Mohit Raina, Mukul Dev",India,"December 1, 2018",2018,TV-14,NaN,"International TV Shows, TV Dramas","In one of history's greatest last stands, a ba...",NaN,NaN,NaN,NaN,NaN
124,s6025,TV Show,7 (Seven),Nizar Shafi,"Rahman, Havish, Regina Cassandra, Nandita Swet...",India,"July 30, 2019",2019,TV-14,NaN,TV Shows,Multiple women report their husbands as missin...,NaN,NaN,NaN,NaN,NaN
130,s5962,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8738,s2645,Movie,"Yours Sincerely, Kanan Gill",Neville Shah,Kanan Gill,India,"April 24, 2020",2020,TV-MA,NaN,Stand-Up Comedy,Revisiting life goals set in a letter written ...,NaN,NaN,NaN,NaN,NaN
8766,s1283,TV Show,Zindagi in Short,NaN,NaN,India,"February 22, 2021",2020,TV-MA,NaN,"International TV Shows, TV Dramas","Complicated marriages, digital romances, domes...",NaN,NaN,NaN,NaN,NaN
8776,s4803,Movie,Zoo,Shlok Sharma,"Shashank Arora, Shweta Tripathi, Rahul Kumar, ...",India,"July 1, 2018",2018,TV-MA,NaN,"Dramas, Independent Movies, International Movies",A drug dealer starts having doubts about his t...,NaN,NaN,NaN,NaN,NaN
8797,s5969,Movie,​Goli Soda 2,Vijay Milton,"Samuthirakani, Bharath Seeni, Vinoth, Esakki B...",India,"September 15, 2018",2018,TV-14,128 min,"Action & Adventure, Dramas, International Movies","A taxi driver, a gangster and an athlete strug...",NaN,NaN,NaN,NaN,NaN
8801,s4668,Movie,​​Kuch Bheege Alfaaz,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 4: ¿Qué títulos tienen clasificación 'TV-14' o 'R'?

In [202]:
condicion_TV14 = df_union_final["rating"] == "TV-14"
condicion_R = df_union_final["rating"] == "R"

df_rating = df_union_final[condicion_TV14 | condicion_R]
df_rating

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
1,s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,NaN,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol...",NaN,NaN,NaN,NaN,NaN
4,s5974,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,NaN,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...,NaN,NaN,NaN,NaN,NaN
9,s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...,NaN,NaN,NaN,NaN,NaN
10,s5278,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,NaN,Comedies,When nerdy high schooler Dani finally attracts...,NaN,NaN,NaN,NaN,NaN
16,s5981,Movie,1 Mile to You,Leif Tilden,"Billy Crudup, Graham Rogers, Liana Liberato, S...",United States,"July 7, 2017",2017,TV-14,NaN,"Dramas, Romantic Movies, Sports Movies",After escaping the bus accident that killed hi...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8798,s5970,Movie,​Maj Rati ​​Keteki,Santwana Bardoloi,"Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...",India,"September 15, 2018",2017,TV-14,117 min,"Dramas, International Movies",A successful writer returns to the town that l...,NaN,NaN,NaN,NaN,NaN
8799,s5971,Movie,​Mayurakshi,Atanu Ghosh,"Soumitra Chatterjee, Prasenjit Chatterjee, Ind...",India,"September 15, 2018",2017,TV-14,NaN,"Dramas, International Movies",When a middle-aged divorcee returns to Kolkata...,NaN,NaN,NaN,NaN,NaN
8800,s2999,TV Show,​SAINT SEIYA: Knights of the Zodiac,NaN,"Bryson Baugus, Emily Neves, Blake Shepard, Pat...",Japan,"January 23, 2020",2020,TV-14,2 Seasons,"Anime Series, International TV Shows",Seiya and the Knights of the Zodiac rise again...,NaN,NaN,NaN,NaN,NaN
8801,s4668,Movie,​​Kuch Bheege Alfaaz,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...,NaN,NaN,NaN,NaN,NaN
8803,s4915,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-14,NaN,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh...",NaN,NaN,NaN,NaN,NaN

#### Ejercicio 5: ¿Cuáles son los títulos dirigidos por 'Christopher Nolan' o 'Martin Scorsese'? ¿Cuántos ha dirigido cada uno de los directores?

In [203]:
filtro_directores = ["Christopher Nolan", "Martin Scorsese"]

df_directores = df_union_final[df_union_final["director"].isin(filtro_directores)]

count_nolan = df_directores["director"].value_counts()
print(count_nolan)
df_directores

director
Martin Scorsese      12
Christopher Nolan     1
Name: count, dtype: int64

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
425,s6112,Movie,Alice Doesn't Live Here Anymore,Martin Scorsese,"Ellen Burstyn, Kris Kristofferson, Billy Green...",United States,"July 1, 2019",1974,PG,112 min,"Classic Movies, Comedies, Dramas",A widowed singer and single mother starts over...,NaN,NaN,NaN,NaN,NaN
2653,s6827,Movie,Gangs of New York,Martin Scorsese,"Leonardo DiCaprio, Daniel Day-Lewis, Cameron D...","United States, Italy","August 20, 2019",2002,R,167 min,Dramas,In the crime-ridden slums of New York in the 1...,NaN,NaN,NaN,NaN,NaN
2803,s6881,Movie,GoodFellas,Martin Scorsese,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...",United States,"January 1, 2021",1990,R,145 min,"Classic Movies, Dramas",Former mobster Henry Hill recounts his colorfu...,NaN,NaN,NaN,NaN,NaN
3215,s2861,Movie,Hugo,Martin Scorsese,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","United Kingdom, United States, France","March 1, 2020",2011,PG,127 min,"Children & Family Movies, Dramas","Living inside a Paris train station, an orphan...",NaN,NaN,NaN,NaN,NaN
3360,s341,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...","United States, United Kingdom","August 1, 2021",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers",A troubled thief who extracts secrets from peo...,NaN,NaN,NaN,NaN,NaN
4502,s7432,Movie,Mean Streets,Martin Scorsese,"Robert De Niro, Harvey Keitel, David Proval, A...",United States,"July 1, 2019",1973,R,112 min,"Classic Movies, Dramas, Independent Movies","In New York's Little Italy, a low-level hoodlu...",NaN,NaN,NaN,NaN,NaN
5073,s2633,Movie,No Direction Home: Bob Dylan,Martin Scorsese,"Bob Dylan, Joan Baez, Dave Van Ronk, Peter Yar...","United Kingdom, United States, Japan","April 25, 2020",2005,TV-MA,208 min,"Documentaries, Music & Musicals",Featuring rare concert footage and interviews ...,NaN,NaN,NaN,NaN,NaN
5704,s7821,Movie,Raging Bull,Martin Scorsese,"Robert De Niro, Cathy Moriarty, Joe Pesci, Fra...",United States,"October 1, 2019",1980,R,129 min,"Classic Movies, Dramas, Sports Movies",This gritty biopic of brutal boxer Jake LaMott...,NaN,NaN,NaN,NaN,NaN
5922,s3760,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,"Bob Dylan, Allen Ginsberg, Joan Baez, Patti Sm...",United States,"June 12, 2019",2019,TV-MA,142 min,"Documentaries, Music & Musicals","In an alchemic mix of fact and fantasy, Martin...",NaN,NaN,NaN,NaN,NaN
6302,s1359,Movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States,"February 1, 2021",2010,R,139 min,Thrillers,A U.S. marshal's troubling visions compromise ...,NaN,NaN,NaN,NaN,NaN
7078,s8273,Movie,The Departed,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...","United States, Hong Kong","January 1, 2021",2006,R,NaN,"Dramas, Thrillers",Two rookie Boston cops are sent deep undercove...,NaN,NaN,NaN,NaN,NaN
7319,s3228,Movie,The Irishman,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Harvey K...",United States,"November 27, 2019",2019,R,209 min,Dramas,Hit man Frank Sheeran looks back at the secret...,Crime drama,"November 27, 2019",209.0,7.8,English
8586,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,"Zina Bethune, Harvey Keitel, Anne Collette, Le...",United States,"July 1, 2019",1967,R,90 min,"Classic Movies, Dramas, Independent Movies",A woman's revelation that she was once raped s...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 6: ¿Qué títulos pertenecen a los países 'United States', 'United Kingdom' o 'Canada'? Dentro de estos países, ¿cuántas películas tienen más de un lenguaje?

In [204]:
filtro_titulos = ["United States", "United Kingdom", "Canada"]

df_titulos = df_union_final[df_union_final["country"].isin(filtro_titulos)]
df_titulos.value_counts("Language")
#Dos películas.

Language
English                       277
English/Spanish                 2
English/Akan                    1
English/Arabic                  1
English/Hindi                   1
English/Japanese                1
English/Mandarin                1
English/Russian                 1
English/Taiwanese/Mandarin      1
French                          1
Japanese                        1
Portuguese                      1
Spanish                         1
Spanish/English                 1
Name: count, dtype: int64

#### Ejercicio 7: ¿Qué títulos fueron lanzados entre 2015 y 2020, inclusive?

In [205]:
filtro_fecha = [2015, 2016, 2017, 2018, 2019, 2020]

df_fecha = df_union_final[df_union_final["release_year"].isin(filtro_fecha)]
df_fecha

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
0,s2037,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,NaN,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ...",NaN,NaN,NaN,NaN,NaN
1,s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,NaN,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol...",NaN,NaN,NaN,NaN,NaN
2,s2482,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,NaN,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ...",NaN,NaN,NaN,NaN,NaN
3,s2325,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...,NaN,NaN,NaN,NaN,NaN
4,s5974,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,NaN,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s4668,Movie,​​Kuch Bheege Alfaaz,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...,NaN,NaN,NaN,NaN,NaN
8803,s4915,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-14,NaN,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh...",NaN,NaN,NaN,NaN,NaN
8804,s7102,TV Show,마녀사냥,NaN,"Si-kyung Sung, Se-yoon Yoo, Dong-yup Shin, Ji-...",South Korea,"February 19, 2018",2015,TV-MA,NaN,"International TV Shows, Korean TV Shows, Stand...",Four Korean celebrity men and guest stars of b...,NaN,NaN,NaN,NaN,NaN
8805,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...,NaN,NaN,NaN,NaN,NaN
8806,s7109,Movie,최강전사 미니특공대 : 영웅의 탄생,Young Jun Lee,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,"September 1, 2018",2018,TV-Y7,68 min,Children & Family Movies,"Miniforce, a special task force of elite range...",NaN,NaN,NaN,NaN,NaN

#### Ejercicio 8: ¿Cuáles son los títulos cuya puntuación en IMDb está entre 6.5 y 8.0 y que no sepamos cual es su duración?

In [206]:
df_puntuacion = df_union_final[df_union_final["IMDB Score"].between(6.5, 8.0, inclusive = "both" )]
df_puntuacion

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
70,s4523,Movie,22 July,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ...",Drama,"October 10, 2018",144.0,6.8,English
129,s5744,Movie,7 años,Roger Gual,"Paco León, Juana Acosta, Juan Pablo Raba, Alex...",Spain,"October 27, 2016",2016,TV-MA,77 min,"Dramas, International Movies",Loyalties are tested and cruelties revealed wh...,Drama,"October 28, 2016",76.0,6.8,Spanish
146,s3366,Movie,A 3 Minute Hug,Everardo González,NaN,"Mexico, United States","October 28, 2019",2019,TV-PG,28 min,"Documentaries, International Movies",This documentary captures the joy and heartbre...,Documentary,"October 28, 2019",28.0,6.5,English/Spanish
177,s5060,Movie,A Futile and Stupid Gesture,David Wain,"Will Forte, Domhnall Gleeson, Martin Mull, Joe...",United States,"January 26, 2018",2018,TV-MA,NaN,Comedies,"In a brief life full of triumph and failure, ""...",Biographical/Comedy,"January 26, 2018",101.0,6.8,English
198,s2787,Movie,A Life of Speed: The Juan Manuel Fangio Story,Francisco Macri,NaN,Argentina,"March 20, 2020",2020,TV-14,NaN,"Documentaries, International Movies, Sports Mo...","Juan Manuel Fangio was the Formula One king, w...",Documentary,"March 20, 2020",92.0,6.8,Spanish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8322,s3413,Movie,Upstarts,Udai Singh Pawar,"Priyanshu Painyuli, Chandrachoor Rai, Shadab K...",India,"October 18, 2019",2019,TV-14,112 min,"Comedies, Dramas, International Movies","Hoping to do good while making millions, three...",Drama,"October 18, 2019",112.0,6.7,Hindi
8522,s5907,Movie,"What Happened, Miss Simone?",Liz Garbus,NaN,United States,"June 26, 2015",2015,TV-14,NaN,"Documentaries, Music & Musicals","Using never-before-heard recordings, rare arch...",Documentary,"June 26, 2015",84.0,7.6,English
8534,s1412,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",Documentary,"January 15, 2021",32.0,6.6,English
8694,s2899,Movie,Yeh Ballet,Sooni Taraporevala,"Julian Sands, Manish Chauhan, Achintya Bose, J...",India,"February 21, 2020",2020,TV-MA,117 min,"Dramas, International Movies","Discovered by an eccentric ballet master, two ...",Drama,"February 21, 2020",117.0,7.6,Hindi
8768,s4708,Movie,Zion,Floyd Russ,Zion Clark,United States,"August 10, 2018",2018,TV-PG,12 min,"Documentaries, Sports Movies",Born without legs and stuck in foster care for...,Documentary,"August 10, 2018",11.0,7.2,English

#### Ejercicio 9: ¿Cuáles son las películas cuya duración de 90 y 150 minutos?

In [207]:
df_duracion = df_union_final.query('duration == "90 min" or duration == "150 min"') 
df_duracion

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
9,s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...,NaN,NaN,NaN,NaN,NaN
29,s5986,Movie,12 ROUND GUN,Sam Upton,"Sam Upton, Jared Abrahamson, Mark Boone Junior...",United States,"March 14, 2019",2017,TV-MA,90 min,"Dramas, Independent Movies, Sports Movies",Dealing with personal demons and the death of ...,NaN,NaN,NaN,NaN,NaN
32,s5988,Movie,13 Cameras,Victor Zarcoff,"PJ McCabe, Brianne Moncrief, Sarah Baldwin, Ji...",United States,"August 13, 2016",2015,NR,90 min,"Horror Movies, Independent Movies, Thrillers",Young parents-to-be Claire and Ryan move into ...,NaN,NaN,NaN,NaN,NaN
52,s5995,Movie,1BR,David Marmor,"Nicole Brydon Bloom, Giles Matthey, Taylor Nic...",United States,"August 23, 2020",2019,TV-MA,90 min,"Horror Movies, Independent Movies, Thrillers","Seeking her independence, a young woman moves ...",NaN,NaN,NaN,NaN,NaN
155,s108,Movie,A Champion Heart,David de Vos,"Mandy Grace, David de Vos, Donna Rusch, Devan ...",United States,"September 4, 2021",2018,G,90 min,"Children & Family Movies, Dramas",When a grieving teen must work off her debt to...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8572,s5695,Movie,White Girl,Elizabeth Wood,"Morgan Saylor, Brian 'Sene' Marc, Justin Barth...",United States,"December 2, 2016",2016,TV-MA,90 min,"Dramas, Independent Movies",A college girl romping through New York City i...,NaN,NaN,NaN,NaN,NaN
8586,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,"Zina Bethune, Harvey Keitel, Anne Collette, Le...",United States,"July 1, 2019",1967,R,90 min,"Classic Movies, Dramas, Independent Movies",A woman's revelation that she was once raped s...,NaN,NaN,NaN,NaN,NaN
8682,s1219,Movie,YES DAY,Miguel Arteta,"Jennifer Garner, Edgar Ramírez, Jenna Ortega, ...",United States,"March 12, 2021",2021,PG,90 min,"Children & Family Movies, Comedies",A mom and dad who usually say no decide to say...,NaN,NaN,NaN,NaN,NaN
8697,s8777,Movie,Yellowbird,Christian De Vita,"Dakota Fanning, Seth Green, Christine Baranski...","France, Belgium","August 5, 2015",2014,PG,90 min,"Children & Family Movies, Comedies",An orphaned bird tags along with a flock on th...,NaN,NaN,NaN,NaN,NaN
8749,s2867,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 10: ¿Cuáles son los títulos que contienen la palabra 'Love' en su título y que sean de tipo TV Show?

In [208]:
df_love_filter = df_union_final[(df_union_final['title'].str.contains('Love')) & (df_union_final['type'] == 'TV Show')]
df_love_filter

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
202,s3369,TV Show,A Little Thing Called First Love,NaN,"Lai Kuan-lin, Zhao Jinmai, Wang Runze, Chai We...",China,"October 26, 2019",2019,TV-G,NaN,"International TV Shows, Romantic TV Shows, Tee...",A shy college student with a knack for drawing...,NaN,NaN,NaN,NaN,NaN
203,s1484,TV Show,A Love So Beautiful,NaN,"Kim Yo-han, So Joo-yeon, Yeo Hoi-hyun, Jeong J...",South Korea,"December 28, 2020",2020,TV-PG,NaN,"International TV Shows, Romantic TV Shows, TV ...",Love is as tough as it is sweet for a lovestru...,NaN,NaN,NaN,NaN,NaN
318,s4488,TV Show,Accidentally in Love,NaN,"Junchen Guo, Yi Ning Sun, Yi Qin Zhao, Mu Xuan...",China,"October 19, 2018",2018,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...","Rejecting the demands of her wealthy family, a...",NaN,NaN,NaN,NaN,NaN
363,s6101,TV Show,Age Gap Love,NaN,Fay Ripley,United Kingdom,"July 12, 2019",2017,TV-MA,NaN,"British TV Shows, Reality TV, Romantic TV Shows",Despite the social backlash and challenges tha...,NaN,NaN,NaN,NaN,NaN
378,s2978,TV Show,Ainori Love Wagon: African Journey,NaN,"Becky, Ryo Kato, Karina Maruyama, Kohei Takeda",Japan,"January 30, 2020",2019,TV-14,NaN,"International TV Shows, Reality TV, Romantic T...","To find love, seven strangers leave Japan and ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8451,s2256,TV Show,Was It Love?,NaN,"Song Ji-hyo, Son Ho-jun, Song Jong-ho, Koo Ja-...",South Korea,"July 9, 2020",2020,TV-14,NaN,"International TV Shows, Korean TV Shows, Roman...",When four very different men appear in her lif...,NaN,NaN,NaN,NaN,NaN
8462,s4262,TV Show,Way Back into Love,NaN,"June Tsai, Ray Chang, Lung Shao-hua, Yi-Wen Ye...",Taiwan,"December 24, 2018",2011,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...","After years in the U.S., a Taiwanese immigrant...",NaN,NaN,NaN,NaN,NaN
8506,s2749,TV Show,Well-Intended Love,NaN,"Xu Kaicheng, Simona Wang, Ian Yi, Huang Qian S...",China,"April 1, 2020",2020,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...","To secure a bone marrow donation, an actress d...",NaN,NaN,NaN,NaN,NaN
8525,s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...,NaN,NaN,NaN,NaN,NaN
8542,s2981,TV Show,What the Love! with Karan Johar,NaN,Karan Johar,United States,"January 30, 2020",2020,TV-14,NaN,"International TV Shows, Reality TV, Romantic T...",With help from celebrity guests and a glam squ...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 11: ¿Cuáles son los títulos en los que el director tiene el apellido 'Johnson'?

In [209]:
df_apellido = df_union_final[(df_union_final['director'].str.contains('Johnson', na = False))]
df_apellido

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
411,s4834,Movie,Alex Strangelove,Craig Johnson,"Daniel Doheny, Madeline Weinstein, Antonio Mar...",United States,"June 8, 2018",2018,TV-MA,NaN,"Comedies, Dramas, Independent Movies",High school senior Alex Truelove's plan to los...,Romantic comedy,"June 8, 2018",99.0,6.3,English
688,s3512,Movie,Avengement,Jesse V. Johnson,"Scott Adkins, Craig Fairbrass, Thomas Turgoose...",United Kingdom,"September 17, 2019",2019,TV-MA,NaN,Action & Adventure,"Betrayed by his loan shark brother, a hardened...",NaN,NaN,NaN,NaN,NaN
1219,s6377,Movie,Brick,Rian Johnson,"Joseph Gordon-Levitt, Nora Zehetner, Lukas Haa...",United States,"September 1, 2018",2005,R,110 min,"Independent Movies, Thrillers",Teenage loner Brendan Fry navigates his high s...,NaN,NaN,NaN,NaN,NaN
1364,s5283,Movie,Carrie Pilby,Susan Johnson,"Bel Powley, Nathan Lane, Vanessa Bayer, Gabrie...",United States,"September 5, 2017",2016,TV-MA,98 min,"Comedies, Dramas",A socially awkward 19-year-old genius makes bi...,NaN,NaN,NaN,NaN,NaN
1790,s6554,Movie,Daffedar,Johnson Esthappan,"Tini Tom, Malavikka, Sudheer Karamana, Indrans",India,"July 1, 2018",2017,TV-14,NaN,"Dramas, International Movies",A retired government worker continues to dedic...,NaN,NaN,NaN,NaN,NaN
1975,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentary,"October 2, 2020",90.0,7.5,English
2022,s830,Movie,Dog Gone Trouble,Kevin Johnson,"Big Sean, Pamela Adlon, Lucy Hale, Marissa Jar...",NaN,"May 28, 2021",2021,TV-Y7,NaN,"Children & Family Movies, Comedies",The privileged life of a pampered dog named Tr...,NaN,NaN,NaN,NaN,NaN
2548,s5537,Movie,Frat Star,"Grant S. Johnson, Ippsie Jones","Connor Lawrence, Justin Mark, Cathryn Dylan, C...",United States,"April 10, 2017",2017,TV-MA,85 min,Comedies,A freshman uninterested in joining a fraternit...,NaN,NaN,NaN,NaN,NaN
2571,s6803,Movie,Freshman Year,Jude Okwudiafor Johnson,"Diallo Thompson, Natalia Dominguez, Benjamin A...",United States,"March 3, 2020",2019,TV-PG,104 min,"Dramas, Faith & Spirituality",A devout preacher's son leaves his protective ...,NaN,NaN,NaN,NaN,NaN
2705,s6848,Movie,Ghost Rider,Mark Steven Johnson,"Nicolas Cage, Eva Mendes, Wes Bentley, Sam Ell...","United States, Australia","October 1, 2020",2007,PG-13,110 min,"Action & Adventure, Sci-Fi & Fantasy","After selling his soul to save a loved one, da...",NaN,NaN,NaN,NaN,NaN
3129,s847,Movie,Home,Tim Johnson,"Jim Parsons, Rihanna, Steve Martin, Jennifer L...",United States,"May 25, 2021",2015,PG,NaN,"Children & Family Movies, Comedies, Sci-Fi & F...",When misfit alien Oh mistakenly sends a party ...,NaN,NaN,NaN,NaN,NaN
3143,s2497,Movie,Honeytrap,Rebecca Johnson,"Jessica Sula, Lucien Laviscount, Ntonga Mwanza...",United Kingdom,"May 20, 2020",2014,TV-MA,NaN,"Dramas, Independent Movies","New to London, a naive and desperate teenager ...",NaN,NaN,NaN,NaN,NaN
3630,s4034,Movie,Juanita,Clark Johnson,"Alfre Woodard, Adam Beach, LaTanya Richardson ...",United States,"March 8, 2019",2019,TV-MA,90 min,"Dramas, Independent Movies, Romantic Movies","Burdened by troubles in life and love, a mothe...",Drama,"March 8, 2019",90.0,6.0,English
3887,s7242,Movie,Kung Fu Panda: Holiday,Tim Johnson,"Jack Black, Angelina Jolie, Dustin Hoffman, Ja...",United States,"December 1, 2012",2010,TV-PG,26 min,"Children & Family Movies, Comedies","As preparations for the Winter Feast build, Po...",NaN,NaN,NaN,NaN,NaN
4243,s2053,Movie,"Love, Guaranteed",Mark Steven Johnson,"Rachael Leigh Cook, Damon Wayans Jr., Heather ...",United States,"September 3, 2020",2020,TV-PG,NaN,"Comedies, Independent Movies, Romantic Movies",Sparks fly when a crusading but cash-strapped ...,Romantic comedy,"September 3, 2020",91.0,5.6,English
4310,s7370,Movie,Mad Money,"Callie Khouri, Jesse V. Johnson","Diane Keaton, Queen Latifah, Katie Holmes, Ted...",United States,"November 1, 2019",2008,PG-13,NaN,Comedies,A woman joins the janitorial staff of the Fede...,NaN,NaN,NaN,NaN,NaN
5119,s7623,Movie,Nowhere Boy,Sam Taylor-Johnson,"Aaron Taylor-Johnson, Anne-Marie Duff, Kristin...","United Kingdom, Canada","April 14, 2018",2009,R,NaN,Dramas,"Raised by his aunt since he was a young boy, c...",NaN,NaN,NaN,NaN,NaN
5989,s7913,Movie,S.W.A.T.,Clark Johnson,"Samuel L. Jackson, Colin Farrell, Michelle Rod...",United States,"January 1, 2021",2003,PG-13,117 min,Action & Adventure,A veteran cop is tasked with drafting and trai...,NaN,NaN,NaN,NaN,NaN
6096,s7947,Movie,Savage Dog,Jesse V. Johnson,"Scott Adkins, Juju Chan, Marko Zaror, Vladimir...",United States,"November 1, 2017",2017,TV-MA,NaN,"Action & Adventure, Independent Movies",A former professional boxer serving time in a ...,NaN,NaN,NaN,NaN,NaN
6526,s8083,Movie,Star Wars: Episode VIII: The Last Jedi,Rian Johnson,"Mark Hamill, Carrie Fisher, Adam Driver, Daisy...",United States,"June 26, 2018",2017,PG-13,152 min,"Action & Adventure, Children & Family Movies, ...",As the remnants of the Resistance flee Kylo Re...,NaN,NaN,NaN,NaN,NaN
7070,s4662,Movie,The Debt Collector,Jesse V. Johnson,"Scott Adkins, Louis Mandylor, Vladimir Kulich,...","United Kingdom, United States","September 3, 2018",2018,TV-MA,NaN,Action & Adventure,A broke martial arts instructor takes a side g...,NaN,NaN,NaN,NaN,NaN
7071,s2084,Movie,The Debt Collector 2,Jesse V. Johnson,"Scott Adkins, Louis Mandylor, Vladimir Kulich,...",United States,"August 31, 2020",2020,TV-MA,NaN,Action & Adventure,French and Sue have two days to collect on thr...,NaN,NaN,NaN,NaN,NaN
7769,s2456,Movie,The Stolen,Niall Johnson,"Alice Eve, Jack Davenport, Graham McTavish, St...","United Kingdom, Germany, United Arab Emirates,...","June 1, 2020",2016,TV-14,98 min,Dramas,A well-to-do British woman must venture into N...,NaN,NaN,NaN,NaN,NaN
8028,s4699,Movie,To All the Boys I’ve Loved Before,Susan Johnson,"Lana Condor, Noah Centineo, Janel Parrish, Ann...",United States,"August 17, 2018",2018,TV-14,NaN,"Comedies, International Movies, Romantic Movies",When her secret love letters somehow get maile...,NaN,NaN,NaN,NaN,NaN
8159,s3718,Movie,Triple Threat,"Jesse V. Johnson, Jesse Johnson","Tony Jaa, Iko Uwais, Tiger Chen, Scott Adkins,...","Thailand, China, United States","June 22, 2019",2019,R,NaN,"Action & Adventure, International Movies",A crew of ruthless criminals hired to kill an ...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 12: ¿Tenemos algún documental ('Documentaries') de Mike Tyson?

In [210]:
df_mike = df_union_final[(df_union_final['Genre'] == "Documentaries") & (df_union_final['cast'].str.contains('Mike Tyson', na = False))]
df_mike

#NO

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, Genre, Premiere, Runtime, IMDB Score, Language]
Index: []

#### Ejercicio 13: Selecciona solo las columnas 'title', 'country' y 'release_year' del dataset.

In [211]:
df_union_final[["title", "country", "release_year"]]

                              title      country  release_year
0                            #Alive  South Korea          2020
1     #AnneFrank - Parallel Stories        Italy          2019
2                 #FriendButMarried    Indonesia          2018
3               #FriendButMarried 2    Indonesia          2020
4                             #Roxy       Canada          2018
...                             ...          ...           ...
8802                       忍者ハットリくん        Japan          2012
8803                           海的儿子          NaN          2016
8804                           마녀사냥  South Korea          2015
8805                        반드시 잡는다  South Korea          2017
8806            최강전사 미니특공대 : 영웅의 탄생          NaN          2018

[8807 rows x 3 columns]

#### Ejercicio 14: Filtra las columnas que contienen la palabra 'date'.

In [212]:
df_date = df_union_final.filter(like='date')
df_date

              date_added
0      September 8, 2020
1           July 1, 2020
2           May 21, 2020
3          June 28, 2020
4         April 10, 2019
...                  ...
8802   December 23, 2018
8803      April 27, 2018
8804   February 19, 2018
8805   February 28, 2018
8806   September 1, 2018

[8807 rows x 1 columns]

#### Ejercicio 15: Usando `query()`, filtra todos los títulos del país 'France' con una duración de 80 minutos.

In [213]:
df_15 = df_union_final.query('duration == "80 min" and country == "France"') 
df_15

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
639,s5475,Movie,Arès,Jean-Patrick Benes,"Ola Rapace, Micha Lescot, Thierry Hancisse, Hé...",France,"May 23, 2017",2016,TV-MA,80 min,"Action & Adventure, International Movies, Sci-...",A futuristic France tries to keep its people f...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 16: Filtra los títulos que son películas ('Movie') y fueron lanzados antes de 2010.

In [214]:
df_16 = df_union_final.query('type == "Movie" and  release_year < 2010')
df_16

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
19,s5982,Movie,"10,000 B.C.",Roland Emmerich,"Steven Strait, Camilla Belle, Cliff Curtis, Jo...","United States, South Africa","June 1, 2019",2008,PG-13,NaN,Action & Adventure,Fierce mammoth hunter D'Leh sets out on an imp...,NaN,NaN,NaN,NaN,NaN
43,s5993,Movie,16 Blocks,Richard Donner,"Bruce Willis, Mos Def, David Morse, Jenna Ster...","United States, Germany","November 1, 2019",2006,PG-13,NaN,Action & Adventure,Tasked with escorting a prosecution witness to...,NaN,NaN,NaN,NaN,NaN
44,s5994,Movie,17 Again,Burr Steers,"Zac Efron, Leslie Mann, Matthew Perry, Thomas ...",United States,"January 1, 2021",2009,PG-13,NaN,Comedies,"Nearing a midlife crisis, thirty-something Mik...",NaN,NaN,NaN,NaN,NaN
46,s5961,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,R,119 min,Dramas,After one of his high school students attacks ...,NaN,NaN,NaN,NaN,NaN
48,s5963,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8777,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN
8778,s1056,Movie,Zoot Suit,Luis Valdez,"Daniel Valdez, Edward James Olmos, Charles Aid...",United States,"April 15, 2021",1981,R,NaN,"Cult Movies, Dramas, Music & Musicals","In this drama based on a 1940s trial, the memb...",NaN,NaN,NaN,NaN,NaN
8779,s1833,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,NaN,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,NaN,NaN,NaN,NaN,NaN
8785,s5978,Movie,Æon Flux,Karyn Kusama,"Charlize Theron, Marton Csokas, Jonny Lee Mill...",United States,"February 1, 2018",2005,PG-13,NaN,"Action & Adventure, Sci-Fi & Fantasy","Aiming to hasten an uprising, the leader of an...",NaN,NaN,NaN,NaN,NaN
8793,s2639,Movie,الف مبروك,Ahmed Nader Galal,"Ahmed Helmy, Laila Ezz El Arab, Mahmoud El Fis...",Egypt,"April 25, 2020",2009,TV-14,NaN,"Comedies, Dramas, International Movies","On his wedding day, an arrogant, greedy accoun...",NaN,NaN,NaN,NaN,NaN

#### Ejercicio 17: Encuentra los 10 títulos con las puntuaciones más altas en IMDb.

In [215]:
df_top10 = df_union_final.nlargest(10, "IMDB Score")
df_top10

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
1847,s1887,Movie,David Attenborough: A Life on Our Planet,"Alastair Fothergill, Jonnie Hughes, Keith Scholey",David Attenborough,"United States, United Kingdom","October 4, 2020",2020,PG,84 min,Documentaries,"A broadcaster recounts his life, and the evolu...",Documentary,"October 4, 2020",83.0,9.0,English
6504,s4294,Movie,Springsteen on Broadway,Thom Zimny,Bruce Springsteen,United States,"December 16, 2018",2018,TV-MA,153 min,Music & Musicals,Bruce Springsteen shares personal stories from...,One-man show,"December 16, 2018",153.0,8.5,English
8620,s5894,Movie,Winter on Fire: Ukraine's Fight for Freedom,Evgeny Afineevsky,NaN,"United Kingdom, Ukraine, United States","October 9, 2015",2015,TV-MA,NaN,"Documentaries, International Movies","Over 93 days in Ukraine, what started as peace...",Documentary,"October 9, 2015",91.0,8.4,English/Ukranian/Russian
1746,s5153,Movie,Cuba and the Cameraman,Jon Alpert,NaN,United States,"November 24, 2017",2017,TV-14,NaN,Documentaries,Emmy-winning filmmaker Jon Alpert chronicles t...,Documentary,"November 24, 2017",114.0,8.3,English
1805,s3387,Movie,Dancing with the Birds,Huw Cordey,Stephen Fry,United States,"October 23, 2019",2019,TV-PG,52 min,Documentaries,From ruffling their majestic feathers to naili...,Documentary,"October 23, 2019",51.0,8.3,English
3839,s3274,Movie,Klaus,Sergio Pablos,"Jason Schwartzman, J.K. Simmons, Rashida Jones...","Spain, United Kingdom","November 15, 2019",2019,PG,98 min,"Children & Family Movies, Comedies",A selfish postman and a reclusive toymaker for...,Animation/Christmas/Comedy/Adventure,"November 15, 2019",97.0,8.2,English
6141,s1172,Movie,Seaspiracy,Ali Tabrizi,NaN,United States,"March 24, 2021",2021,TV-14,90 min,Documentaries,"Passionate about ocean life, a filmmaker sets ...",Documentary,"March 24, 2021",89.0,8.2,English
7799,s1858,Movie,The Three Deaths of Marisela Escobedo,Carlos Pérez Osorio,NaN,Mexico,"October 14, 2020",2020,TV-MA,110 min,"Documentaries, International Movies",This documentary examines a mother's tireless ...,Documentary,"October 14, 2020",109.0,8.2,Spanish
1432,s5377,Movie,Chasing Coral,Jeff Orlowski,NaN,United States,"July 14, 2017",2017,TV-PG,NaN,Documentaries,"Divers, scientists and photographers around th...",Documentary,"July 14, 2017",89.0,8.1,English
4887,s2039,Movie,My Octopus Teacher,"Pippa Ehrlich, James Reed",NaN,South Africa,"September 7, 2020",2020,TV-G,NaN,"Children & Family Movies, Documentaries, Inter...",A filmmaker forges an unusual friendship with ...,Documentary,"September 7, 2020",85.0,8.1,English

#### Ejercicio 18: Encuentra los 5 títulos con las puntuaciones más bajas en IMDb.

In [216]:
df_down5 = df_union_final.nsmallest(5, "IMDB Score")
df_down5

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
2263,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...,Documentary,"August 5, 2019",58.0,2.5,English/Japanese
1827,s2105,Movie,Dark Forces,Bernardo Arellano,"Tenoch Huerta, Eréndira Ibarra, Dale Carley, A...",Mexico,"August 21, 2020",2020,TV-MA,81 min,"Horror Movies, Independent Movies, Internation...","In search of his sister, a renegade criminal s...",Thriller,"August 21, 2020",81.0,2.6,Spanish
6860,s3095,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ...",Science fiction/Drama,"December 26, 2019",79.0,2.6,Italian
7568,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son...",Horror thriller,"January 19, 2018",94.0,3.2,English
3684,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...,Mystery,"October 30, 2020",90.0,3.4,Hindi

#### Ejercicio 19: Filtra todos los títulos que no tienen un director asignado (valores nulos en la columna 'director').

In [217]:
df_null_director = df_union_final[df_union_final["director"].isnull()]
df_null_director

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
8,s2667,TV Show,#blackAF,NaN,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,"April 17, 2020",2020,TV-MA,NaN,TV Comedies,Kenya Barris and his family navigate relations...,NaN,NaN,NaN,NaN,NaN
12,s5968,Movie,'89,NaN,"Lee Dixon, Ian Wright, Paul Merson",United Kingdom,"May 16, 2018",2017,TV-PG,NaN,Sports Movies,"Mixing old footage with interviews, this is th...",NaN,NaN,NaN,NaN,NaN
14,s2141,TV Show,(Un)Well,NaN,NaN,United States,"August 12, 2020",2020,TV-MA,NaN,Reality TV,This docuseries takes a deep dive into the luc...,NaN,NaN,NaN,NaN,NaN
20,s1584,TV Show,100 Days My Prince,NaN,"Doh Kyung-soo, Nam Ji-hyun, Cho Seong-ha, Cho ...",South Korea,"December 7, 2020",2018,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...","Upon losing his memory, a crown prince encount...",NaN,NaN,NaN,NaN,NaN
21,s5983,Movie,100 Days Of Solitude,NaN,NaN,Spain,"July 6, 2018",2018,TV-MA,NaN,"Documentaries, International Movies",Spanish photographer José Díaz spends 100 days...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8796,s5975,TV Show,แผนร้ายนายเจ้าเล่ห์,NaN,"Chutavuth Pattarakampol, Sheranut Yusananda, N...",NaN,"March 30, 2019",2016,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...","When two brothers fall for two sisters, they q...",NaN,NaN,NaN,NaN,NaN
8800,s2999,TV Show,​SAINT SEIYA: Knights of the Zodiac,NaN,"Bryson Baugus, Emily Neves, Blake Shepard, Pat...",Japan,"January 23, 2020",2020,TV-14,2 Seasons,"Anime Series, International TV Shows",Seiya and the Knights of the Zodiac rise again...,NaN,NaN,NaN,NaN,NaN
8802,s6178,TV Show,忍者ハットリくん,NaN,NaN,Japan,"December 23, 2018",2012,TV-Y7,2 Seasons,"Anime Series, Kids' TV","Hailing from the mountains of Iga, Kanzo Hatto...",NaN,NaN,NaN,NaN,NaN
8803,s4915,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-14,NaN,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh...",NaN,NaN,NaN,NaN,NaN
8804,s7102,TV Show,마녀사냥,NaN,"Si-kyung Sung, Se-yoon Yoo, Dong-yup Shin, Ji-...",South Korea,"February 19, 2018",2015,TV-MA,NaN,"International TV Shows, Korean TV Shows, Stand...",Four Korean celebrity men and guest stars of b...,NaN,NaN,NaN,NaN,NaN

#### Ejercicio 20: Filtra todos los títulos que tienen información completa en las columnas 'title', 'country' y 'IMDB Score'.

In [220]:
df_completos = df_union_final[df_union_final["title"].notnull() & df_union_final["country"].notnull() & df_union_final["IMDB Score"].notnull()]
df_completos

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language
41,s3963,Movie,15 August,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ...",Comedy-drama,"March 29, 2019",124.0,5.8,Marathi
49,s5208,Movie,1922,Zak Hilditch,"Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...",United States,"October 20, 2017",2017,TV-MA,NaN,"Dramas, Thrillers",A farmer pens a confession admitting to his wi...,Horror/Crime drama,"October 20, 2017",102.0,6.3,English
70,s4523,Movie,22 July,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ...",Drama,"October 10, 2018",144.0,6.8,English
108,s4316,Movie,5 Star Christmas,Marco Risi,"Massimo Ghini, Ricky Memphis, Martina Stella, ...",Italy,"December 7, 2018",2018,TV-14,NaN,"Comedies, International Movies",When the Italian prime minister meets his love...,Comedy,"December 7, 2018",95.0,4.6,Italian
115,s4935,Movie,6 Balloons,Marja Lewis Ryan,"Abbi Jacobson, Dave Franco, Jane Kaczmarek, Ti...",United States,"April 6, 2018",2018,TV-MA,75 min,"Dramas, Independent Movies",A loyal sister struggles to stay afloat while ...,Drama,"April 6, 2018",75.0,5.9,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8649,s2160,Movie,Work It,Laura Terruso,"Sabrina Carpenter, Jordan Fisher, Liza Koshy, ...",United States,"August 7, 2020",2020,TV-14,NaN,Comedies,A brilliant but clumsy high school senior vows...,Dance comedy,"August 7, 2020",93.0,6.1,English
8673,s5810,Movie,XOXO,Christopher Louie,"Sarah Hyland, Graham Phillips, Chris D'Elia, H...",United States,"August 26, 2016",2016,TV-MA,NaN,"Dramas, Music & Musicals","The lives of a budding DJ, his loyal pal, a ho...",Drama,"August 26, 2016",92.0,5.3,English
8694,s2899,Movie,Yeh Ballet,Sooni Taraporevala,"Julian Sands, Manish Chauhan, Achintya Bose, J...",India,"February 21, 2020",2020,TV-MA,117 min,"Dramas, International Movies","Discovered by an eccentric ballet master, two ...",Drama,"February 21, 2020",117.0,7.6,Hindi
8727,s1902,Movie,You've Got This,Salvador Espinosa,"Mauricio Ochmann, Esmeralda Pimentel, Matteo G...",Mexico,"October 2, 2020",2020,TV-MA,112 min,"Comedies, International Movies, Romantic Movies",An ad creative and a successful exec have a gr...,Romantic comedy,"October 2, 2020",111.0,5.8,Spanish
8768,s4708,Movie,Zion,Floyd Russ,Zion Clark,United States,"August 10, 2018",2018,TV-PG,12 min,"Documentaries, Sports Movies",Born without legs and stuck in foster care for...,Documentary,"August 10, 2018",11.0,7.2,English

#### Ejercicio 21: Identifica si hay títulos duplicados en la columna 'title'.

In [ ]:
df_duplicadas = df_union_final["title"].duplicated().sum()
df_duplicadas

np.int64(0)